### ISSUE TITLE
Note to Reviewer

### ISSUE THREAD

**Issue by Atifzada** [adeola003/Recipe_App#12]
#### On this group project, we are two people working together @Atifzada @adeola003 

Here is the [link to our Kanban Board](https://github.com/adeola003/Recipe_App/projects/1)

**Comment by prolajumokeoni** [comment]
Hi @Team
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good setup


## Required Changes ♻️

- [x] Kindly make sure that the tasks on your board are shared equally,  @Atifzada has more cards assigned than @adeola003  
- It will be better for you to add a `Group Task` heading to tasks you want to do together so you can differentiate them from individual tasks, currently, some cards are assigned to you both  and I assume they are group tasks if it is not a group task you can add only the appropriate assignee👍🏿 

- [x] Please add a card to `Make sure there are no N+1 queries happening` on your board 👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Atifzada** [comment]
Thank you for your kind suggestions. Indeed these are the project requirements. We have fixed all the mentioned issues as per your instructions

**Comment by Gambit142** [comment]
Hi @Atifzada @adeola003 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Created Kanban board ✔️ 
- Tasks are assigned and shared in an equal manner ✔️ 
- All project requirements are present in the Kanban board ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
